name: CI

on: pull_request

env:
  NODE_VERSION: 16.0.0

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install modules
        run: npm install

      - name: Run test with coverage
        run: npm run test:coverage

      - name: Lint
        run: npm run lint
